<?php

declare(strict_types=1);

/*
 * Regenerates app/Support/data/timezones.php — the time zones the settings screen offers, Windows-style groups with
 * Persian names from ICU — a developer's tool: it needs ext-intl, which the shop itself does not (it reads the file).
 *
 *   php -d extension=intl scripts/timezones.php
 */

use App\Support\Timezones;

require dirname(__DIR__) . '/vendor/autoload.php';

if (PHP_SAPI !== 'cli') {
    exit;
}
if (!class_exists(IntlTimeZone::class)) {
    fwrite(STDERR, "ext-intl is not loaded: run `php -d extension=intl scripts/timezones.php`.\n");
    exit(1);
}

$rows = collect_zones();
file_put_contents(dirname(__DIR__) . '/' . Timezones::DATA_FILE, export_zones($rows));
fwrite(STDOUT, sprintf("%d zones written to %s\n", count($rows), Timezones::DATA_FILE));

/** @return list<array{id: string, offset: int, name: string, ids: list<string>}> */
function collect_zones(): array
{
    $known = array_flip(DateTimeZone::listIdentifiers());
    $plain = static fn(string $s): string => (string) preg_replace('/[\x{064B}-\x{0655}\x{0670}]/u', '', str_replace("\u{06C0}", "\u{0647}", $s));
    $farsi = static fn(string $s): bool => $s !== '' && preg_match('/\p{Arabic}/u', $s) === 1 && !str_contains($s, '/');

    $groups = [];
    foreach (array_keys($known) as $id) {
        $windows = IntlTimeZone::getWindowsID($id);
        if ($windows !== false && $windows !== '') {
            $groups[$windows][] = $id;
        }
    }

    $rows = [];
    foreach ($groups as $windows => $ids) {
        $icuCanonical = (string) IntlTimeZone::getIDForWindowsID($windows);
        $canonical = $windows === 'UTC' ? 'UTC' : (isset($known[$icuCanonical]) ? $icuCanonical : $ids[0]);
        $tz = IntlTimeZone::createTimeZone($canonical);

        // "وقت عادی ژاپن" (standard time) reads oddly as a zone name; Windows does not say "standard" either.
        $zone = (string) preg_replace('/^وقت عادی\s+/u', 'وقت ', $plain($tz->getDisplayName(false, IntlTimeZone::DISPLAY_LONG_GENERIC, 'fa')));
        if (!$farsi($zone)) {
            $zone = '';
        }

        $places = [];
        foreach (array_unique(array_merge([$canonical], $ids)) as $member) {
            $name = $plain((string) preg_replace('/^وقت\s+/u', '', IntlTimeZone::createTimeZone($member)->getDisplayName(false, IntlTimeZone::DISPLAY_GENERIC_LOCATION, 'fa')));
            $name = trim(explode('،', $name)[0]); // "ناکس، ایندیانا" → "ناکس"
            if ($farsi($name) && !in_array($name, $places, true) && !str_contains($zone, $name)) {
                $places[] = $name;
            }
        }

        $rows[] = ['id' => $canonical, 'offset' => intdiv($tz->getRawOffset(), 1000), 'zone' => $zone, 'places' => $places, 'ids' => array_values(array_diff($ids, [$canonical]))];
    }

    // A zone name shared by several groups at the same offset needs its places to tell them apart.
    $counts = [];
    foreach ($rows as $row) {
        $counts[$row['offset'] . '|' . $row['zone']] = ($counts[$row['offset'] . '|' . $row['zone']] ?? 0) + 1;
    }

    $result = [];
    foreach ($rows as $row) {
        $shared = $row['zone'] === '' || $counts[$row['offset'] . '|' . $row['zone']] > 1;
        $short = implode('، ', array_slice($row['places'], 0, 3)) . (count($row['places']) > 3 ? '…' : '');
        $name = match (true) {
            $row['id'] === 'UTC' => 'زمان جهانی هماهنگ',
            $row['zone'] === '' => $short,
            $shared && $row['places'] !== [] => $row['zone'] . ' (' . $short . ')',
            default => $row['zone'],
        };
        $result[] = ['id' => $row['id'], 'offset' => $row['offset'], 'name' => $name, 'ids' => $row['ids']];
    }

    usort($result, static fn(array $a, array $b): int => [$a['offset'], $a['name']] <=> [$b['offset'], $b['name']]);

    return $result;
}

/** @param list<array{id: string, offset: int, name: string, ids: list<string>}> $rows */
function export_zones(array $rows): string
{
    $out = "<?php\n\ndeclare(strict_types=1);\n\n";
    $out .= "/*\n * Time zones the settings screen offers, grouped the way Windows groups them: one entry per Windows zone.\n";
    $out .= " * `id` is the IANA identifier stored in APP_TIMEZONE, `offset` the standard (non-DST) UTC offset in seconds,\n";
    $out .= " * `name` the Persian zone name from ICU (with places when the name alone is ambiguous) and `ids` the other\n";
    $out .= " * IANA identifiers of the same group. Generated by `php -d extension=intl scripts/timezones.php`; do not edit by hand.\n */\n";
    $out .= "return [\n";
    foreach ($rows as $row) {
        $ids = implode(', ', array_map(static fn(string $id): string => var_export($id, true), $row['ids']));
        $out .= sprintf("    ['id' => %s, 'offset' => %d, 'name' => %s, 'ids' => [%s]],\n", var_export($row['id'], true), $row['offset'], var_export($row['name'], true), $ids);
    }

    return $out . "];\n";
}
